"""Add relation.

Revision ID: 126e51b1a146
Revises: c12ea15b4cc5
Create Date: 2024-07-01 05:52:45.484825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '126e51b1a146'
down_revision = 'c12ea15b4cc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Quizzes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('text', sa.String(length=128), nullable=True),
    sa.Column('ans', sa.String(length=128), nullable=True),
    sa.Column('cand1', sa.String(length=128), nullable=True),
    sa.Column('cand2', sa.String(length=128), nullable=True),
    sa.Column('cand3', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_quizsets',
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('quizset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['Quizzes.id'], ),
    sa.ForeignKeyConstraint(['quizset_id'], ['QuizSets.id'], ),
    sa.PrimaryKeyConstraint('quiz_id', 'quizset_id')
    )
    op.drop_table('Relations')
    op.drop_table('Quizes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Quizes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('text', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('ans', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('cand1', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('cand2', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('cand3', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Relations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('set', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quiz', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('quiz_quizsets')
    op.drop_table('Quizzes')
    # ### end Alembic commands ###
