"""rsult

Revision ID: 1bb6dc11151b
Revises: 4399ea64a873
Create Date: 2024-07-22 04:36:49.815447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb6dc11151b'
down_revision = '4399ea64a873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Result', schema=None) as batch_op:
        batch_op.drop_column('total')
        batch_op.drop_column('score')

    # ### end Alembic commands ###
