"""Second migration.

Revision ID: 3be4a00bebf9
Revises: 934340c4dddf
Create Date: 2024-06-28 02:45:45.546467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be4a00bebf9'
down_revision = '934340c4dddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('text', sa.String(length=128), nullable=True),
    sa.Column('ans', sa.String(length=128), nullable=True),
    sa.Column('cand1', sa.String(length=128), nullable=True),
    sa.Column('cand2', sa.String(length=128), nullable=True),
    sa.Column('cand3', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set', sa.Integer(), nullable=True),
    sa.Column('quiz', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relation')
    op.drop_table('quiz_set')
    op.drop_table('quiz')
    # ### end Alembic commands ###
