"""result2

Revision ID: 67d56233cb74
Revises: b1fbf28d0f2c
Create Date: 2024-07-22 05:11:18.463266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67d56233cb74'
down_revision = 'b1fbf28d0f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Result', schema=None) as batch_op:
        batch_op.drop_column('true_answers')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('true_answers', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
