"""result1

Revision ID: b1fbf28d0f2c
Revises: e22c251557fa
Create Date: 2024-07-22 05:05:25.511549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1fbf28d0f2c'
down_revision = 'e22c251557fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('true_answers', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Result', schema=None) as batch_op:
        batch_op.drop_column('true_answers')

    # ### end Alembic commands ###
