"""Third migration.

Revision ID: c12ea15b4cc5
Revises: 3be4a00bebf9
Create Date: 2024-06-28 03:50:28.731693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c12ea15b4cc5'
down_revision = '3be4a00bebf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('QuizSets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Quizes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('text', sa.String(length=128), nullable=True),
    sa.Column('ans', sa.String(length=128), nullable=True),
    sa.Column('cand1', sa.String(length=128), nullable=True),
    sa.Column('cand2', sa.String(length=128), nullable=True),
    sa.Column('cand3', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set', sa.Integer(), nullable=True),
    sa.Column('quiz', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('quiz')
    op.drop_table('quiz_set')
    op.drop_table('relation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relation',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('set', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quiz', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('quiz_set',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('author', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('quiz',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('text', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('ans', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('cand1', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('cand2', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('cand3', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Relations')
    op.drop_table('Quizes')
    op.drop_table('QuizSets')
    # ### end Alembic commands ###
