apiVersion: v1
kind: Service
metadata:
  labels:
    app: asalab-web
  name: asalab-web
spec:
  selector:
    app: asalab-web
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP