apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: asalab-web
  name: asalab-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asalab-web
  template:
    metadata:
      labels:
        app: asalab-web
    spec:
      containers:
      - image: shushioiri/asalab-web
        name: asalab-web